[package]
name = "emucore"
version = "0.1.0"
authors = ["Nyrox <root@nyrox.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck="*"
derivative="2.1.1"
num-traits="*"


[workspace]
members=[".", "cli"]
